name: "unit tests"

on: ["pull_request", "push"]

jobs:
    unit-tests:
        name: "unit tests ${{ matrix.php-version }} ${{ matrix.dependencies }}"

        runs-on: ubuntu-latest

        strategy:
            fail-fast: false
            matrix:
                php-version:
                    - "8.1"
                    - "8.2"
                    - "8.3"
                    - "8.4"
                dependencies: ["highest"]
                include:
                  - php-version: "8.4"
                    dependencies: "lowest"

        steps:
            - name: "checkout"
              uses: "actions/checkout@v4"

            - name: "installing PHP"
              uses: "shivammathur/setup-php@v2"
              with:
                  php-version: "${{ matrix.php-version }}"
                  ini-values: memory_limit=-1
                  tools: composer:v2, cs2pr

            - name: "installing dependencies"
              run: "composer update --no-interaction --no-progress --no-suggest ${{ matrix.dependencies == 'lowest' && '--prefer-lowest' || '' }}"

            - name: "running unit tests"
              env:
                SYMFONY_DEPRECATIONS_HELPER: ${{ matrix.php-version == '8.4' && 'disabled=1' || '' }}
              run: "php vendor/bin/simple-phpunit"
